### ISSUE TITLE
Layout Grid/Bauhaus: text domain doesn't match slug

### ISSUE THREAD

**Issue by ajlende** [Automattic/block-experiments#10]
I had the Bauhaus block bounce back because the Text Domain in the generated index.php file didn't match up with the slug, so I checked and it appears the same is true for the layout grid.

In the case of Layout Grid, the Text Domain is prefixed `jetpack-`, whereas the slug is not. I suppose in the grid case, since the slug cannot be changed, the prefix should be removed. However, the slug hasn't been finalized yet for the Bauhaus block, so should it use the `jetpack-` prefix here?

**Comment by johngodley** [comment]
Bounced back from... the .org repo? We don't have any text that needs translating so we could just remove the line.

**Comment by ajlende** [comment]
Yeah, the Bauhaus block plugin wasn't approved for .org because they didn't match. The change is simply renaming the [resource field](https://github.com/Automattic/block-experiments/blob/master/bundler/bundles/layout-grid.json#L8) to match the slug in the Layout Grid case, which I can do. Just need to know if the slug should say jetpack for Bauhaus before I get it approved.

**Comment by johngodley** [comment]
The text domain field [isn't needed](https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#text-domains) so if we remove it then it doesn't matter what the plugin slug is.

As to what the slug for Bauhaus should be... I'll leave that to @mkaz. Noting that for Layout Grid we haven't named it in Jetpack in the repo, even though it uses that internally for the block name.
