### ISSUE TITLE
Image Tools: instant rotate while processing

### ISSUE THREAD

**Issue by johngodley** [Automattic/block-experiments#15]
It would be great if we could instantly rotate the image while the actual rotation happens in the background.

I've previously tried:
- CSS rotation - works, but the height is then wrong and the UI needs a lot of adjusting
- Canvas rotation - copy the image to a canvas and rotate it. Complicated

**Comment by ajlende** [comment]
The Rich Image block has moved to the Gutenberg [Image Block](https://github.com/WordPress/gutenberg/tree/master/packages/block-library/src/image). This issue is being tracked by https://github.com/WordPress/gutenberg/pull/23569
