### ISSUE TITLE
Layout Grid: Appears broken in the full-site editor

### ISSUE THREAD

**Issue by kjellr** [Automattic/block-experiments#154]
Testing with Gutenberg 9.3.0, the Layout Grid block appears broken in the full-site editor. Instead of stretching to fill the container, each column only takes up a fraction of the available horizontal space. 

Post/Page Editor (As expected)|Site Editor (columns don't fill available space)
---|---
![Screen Shot 2020-11-10 at 11 16 30 AM](https://user-images.githubusercontent.com/1202812/98700493-3c394080-2346-11eb-821c-e29eadb1fe21.png)|![Screen Shot 2020-11-10 at 11 10 02 AM](https://user-images.githubusercontent.com/1202812/98699689-66d6c980-2345-11eb-826a-5e2f6abd3cc5.png)

**Tested with:**

[Seedlet Blocks](https://github.com/Automattic/themes/tree/trunk/seedlet-blocks), [Twenty Twenty-One Blocks](https://github.com/WordPress/theme-experiments/tree/master/twentytwentyone-blocks) 
Gutenberg 9.3.0
Safari 14.0

**Comment by jasmussen** [comment]
Thanks for the report! Fix in #156.

**Comment by johngodley** [comment]
The fix has been deployed

**Comment by jasmussen** [comment]
:milkshake:
