### ISSUE TITLE
Layout Grid: Fatal error when deleting content on small screen

### ISSUE THREAD

**Issue by roo2** [Automattic/block-experiments#158]
This is an interesting one, it only seems to affect deleting content using a delete key on a small screen, this may not actually happen often in the wild, but I feel it's worth investigating in case there is another way to trigger this error.

### To Reproduce:

* Open an editor
* Resize the browser to **under 700px width**
* Add a Layout Grid block
* In one of the columns, add an image
* Delete the image **with the delete key** (not through the UI)

Observe a fatal error and in the console:

`TypeError: Cannot read property 'name' of null`

![Dec-09-2020 15-09-23](https://user-images.githubusercontent.com/22446385/101587785-a5d56900-3a30-11eb-879f-5dc775d6fd7a.gif)

**Comment by jasmussen** [comment]
Wow, good one. Confirmed. I get this full JS error in the console:

<img width="1604" alt="Screenshot 2020-12-09 at 08 46 49" src="https://user-images.githubusercontent.com/1204802/101600132-2a0cf980-39fb-11eb-8491-fc5c752dfaeb.png">

However it appears this isn't a bug with Layout Grid, but indeed _any block with nesting in the core editor itself_. Here's the Columns block exhibiting the same behavior:

![cols](https://user-images.githubusercontent.com/1204802/101600302-6a6c7780-39fb-11eb-8c48-8339301aacb3.gif)

I suspect it's a recent change to handling transforms, which does not take into account that the toolbar is forced to the top on small screens.

@roo2 would you mind creating a ticket in the upstream repo? https://github.com/WordPress/gutenberg/issues

**Comment by roo2** [comment]
raised https://github.com/WordPress/gutenberg/issues/27833

**Comment by jasmussen** [comment]
Thank you. Closing this one as upstream.
