### ISSUE TITLE
Layout Grid: Doesn't work with block based themes

### ISSUE THREAD

**Issue by david-szabo97** [Automattic/block-experiments#170]
Layout Grid doesn't work with block-based themes. `front.css` isn't loaded on the front at all.

Looks like we are registering the stylesheet on `wp_enqueue_scripts` action:

https://github.com/Automattic/block-experiments/blob/7ca7c4d20c45699069a1fe3b3d1fd3e2e2423710/blocks/layout-grid/index.php#L29-L34

We should consider moving this into `init` right before `register_block_type( 'jetpack/layout-grid', [`.

**Comment by johngodley** [comment]
What is a block based theme?

It was moved away from `init` as it caused other problems.

**Comment by johngodley** [comment]
Can you give an example of a theme/site this is happening on?

**Comment by jasmussen** [comment]
You can get some block based themes in https://github.com/WordPress/theme-experiments. Otherwise, "TT1 Blocks" which comes with the gutenberg core install. I can help you set this up if need be.

**Comment by david-szabo97** [comment]
Site: Pck32F-5-p2

Editor:
![image](https://user-images.githubusercontent.com/2256104/109850056-60e95900-7c52-11eb-9ae7-ef71095b66d9.png)

Front: 
![image](https://user-images.githubusercontent.com/2256104/109850091-6a72c100-7c52-11eb-9900-2b35a0479d47.png)

**Comment by alaczek** [comment]
You can also check it out on this site: https://fsecassel.wordpress.com/
This post has a link to start a new site with FSE enabled (and lets you pick one of the block-based themes in signup):
p7DVsv-ayb-p2

**Comment by alaczek** [comment]
Thank you, thank you! Any idea when would this be available on simple sites?

**Comment by johngodley** [comment]
@alaczek I've added you to the phab diff
