### ISSUE TITLE
Layout block: Hyphens Mobile Safari

### ISSUE THREAD

**Issue by joweber123** [Automattic/block-experiments#173]
### Steps to reproduce the behavior

1. Add a Layout Block to a page. 
2. Inside of this block, add a heading block with a long text.  Here is an example - "My name is James and I am a Happiness Engineer at Automattic."
3. Publish the page a view it in Safari on mobile. 

#### What I expected to happen
On other mobile browsers, words are breaking with no hyphens.

#### What actually happened
In Safari, the CSS is currently set to `-webkit-hyphens: auto;` when I believe it should be set to `-webkit-hyphens: none;`.  

### Context
3702064-zen

#### Browser / OS version

Model: iPhone (seems to affect any model)
Browser:Safari
IOS: 13.1.3 (this is the current version that is available in Safari's **Responsive Design Mode**

#### Is this specific to the applied theme? Which one?
I can reproduce this on any theme I have tested so far.  The CSS is coming from the block itself.  

#### Does this happen on simple or atomic sites or both?
Both

#### Is there any console output or error text?
None

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
This affects all users in Safari that are currently using this block.  We can provide the following CSS to temporarily resolve this for the user.

```
.site-content .wp-block-jetpack-layout-grid .wp-block-jetpack-layout-grid-column *{
    -webkit-hyphens: none;
}
```

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
![Markup on 2021-02-06 at 14:36:36](https://user-images.githubusercontent.com/24914028/107110123-bf582d00-6888-11eb-9bbb-3dbc3089ae2e.png)

**Comment by jasmussen** [comment]
Thanks for the report. This is intentional as of https://github.com/Automattic/block-experiments/issues/155. The layout will break if we do not hyphenate the text.

**Comment by kriskorn** [comment]
@jasmussen That has created a lot of support requests, because it creates unintentional word-breaks, which users do not like one bit. If possible, the hyphenation should be a setting or changed back. Will update this in a bit with some analysis.

**Comment by jasmussen** [comment]
I don't mean to dismiss the feedback, it's just that we have three options at this point, and all of them have downsides:

1: The current setup:

<img width="982" alt="Screenshot 2021-03-04 at 11 56 09" src="https://user-images.githubusercontent.com/1204802/109953643-9f2d5980-7ce0-11eb-856c-fcde26ee4737.png">

In this setup, words with a large font size are hyphenated and wrap.

2: The current setup, but without hyphens:

<img width="982" alt="Screenshot 2021-03-04 at 11 56 47" src="https://user-images.githubusercontent.com/1204802/109953705-b704dd80-7ce0-11eb-89e8-d8025dfd2ee5.png">

In doing that, we'll effectively need to reopen https://github.com/Automattic/block-experiments/issues/155

3: No forced wrapping, no hyphenation:

<img width="938" alt="Screenshot 2021-03-04 at 11 57 17" src="https://user-images.githubusercontent.com/1204802/109953796-cd129e00-7ce0-11eb-9dfa-05888e5ba606.png">

I'm happy to turn hyphenation off again if you believe it stems support requests. But I don't think it solves the fundamental problem. Longer term [better responsive tools](https://github.com/WordPress/gutenberg/issues/19909) can help make smart defaults, and in the nearer term it makes sense to look at the patterns that are use, which cause these issues, and perhaps use smaller font sizes.
