### ISSUE TITLE
Layout Grid: In Firefox, Cover block text overflows beyond the layout grid

### ISSUE THREAD

**Issue by jeyip** [Automattic/block-experiments#176]
## Description
The original issue https://github.com/Automattic/wp-calypso/issues/47247 was moved into this repo for more appropriate tracking.

In Firefox, if you add Cover blocks within the columns of a Layout grid, the Cover block height is incorrect in the site's frontend. The result is Cover block content overflowing outside of the cover block container.

## Steps to Reproduce
1. Starting at URL: Simple or AT site
2. Add a Layout Grid block to the page
3. Add Cover blocks in each column, make one larger with the content (no size set on the Cover blocks)
4. Verify the bug in Firefox

### Editor Setup
![https://d.pr/i/llMnTL](https://d.pr/i/llMnTL+)

### Website Frontend
![https://d.pr/i/eLdBE9](https://d.pr/i/eLdBE9+)

## Browser / OS version
macOS Catalina 10.15.5 (19F101)
Firefox: 81.0.1 (64-bit)

## Context / Source
25354840-hc

**Comment by johngodley** [comment]
This is fixed by https://github.com/Automattic/block-experiments/pull/174. It will appear in the plugin in version 1.6

**Comment by mikeicode** [comment]
Still running into this (I assume it's still being worked on by the comments on the link above).

3928337-zd-woothemes
