### ISSUE TITLE
Layout Grid: drag handle jumps when clicked

### ISSUE THREAD

**Issue by johngodley** [Automattic/block-experiments#194]
Not sure when this happened, but the grid drag handle jumps when it is selected. Here's the unselected state:

![image](https://user-images.githubusercontent.com/1277682/118648592-7d6d4a00-b7da-11eb-8298-dcd58269fbfa.png)

Here's when dragging:

![image](https://user-images.githubusercontent.com/1277682/118648650-8c53fc80-b7da-11eb-83b9-dd6422c214cf.png)

**Comment by jasmussen** [comment]
Hmm. I'm not able to reproduce this in Chrome:

![chrome](https://user-images.githubusercontent.com/1204802/119482802-933bbb80-bd54-11eb-965c-d648643c3688.gif)

That said, I'm seeing weirdness in Safari.... different to what's shown here but nevertheless:

![saf](https://user-images.githubusercontent.com/1204802/119482905-b1a1b700-bd54-11eb-9df9-a4eb435545d6.gif)

Do you have more steps?

**Comment by johngodley** [comment]
I think it might be a theme problem. It happens consistently with the 'Balsana' theme, but 'Edda' works fine (on wp.com). I haven't tried many others. Is that kind of thing something we should fix here, or is it a theme fix?

**Comment by jasmussen** [comment]
Confirmed, #197 will fix this because it adds `position: relative;` to one of the containers:

![hey](https://user-images.githubusercontent.com/1204802/119488276-a5205d00-bd5a-11eb-8296-46e3b1f7e1a3.gif)

**Comment by johngodley** [comment]
Magic!

**Comment by jasmussen** [comment]
(⊃｡•́‿•̀｡)⊃━☆ﾟ.*･｡ﾟ

**Comment by johngodley** [comment]
Closing as fixed by #197
