### ISSUE TITLE
Layout Grid: Contents in the Layout Grid block are being excluded from the excerpt

### ISSUE THREAD

**Issue by danieldudzic** [Automattic/block-experiments#245]
This has been originally reported here: https://github.com/Automattic/wp-calypso/issues/54046

I was able to track the issue down to the `excerpt_allowed_wrapper_blocks` array.

I don't know if the Layout Grid contents are being intentionally excluded from the excerpt generation - if that's not the case, we should probably allow it, as it is confusing users.

`'jetpack/layout-grid', 'jetpack/layout-grid-column',` should be added to the list via `excerpt_allowed_wrapper_blocks` filter.

**Comment by supernovia** [comment]
Noting in this can cause people's RSS feeds to break

**Comment by johngodley** [comment]
> I don't know if the Layout Grid contents are being intentionally excluded from the excerpt generation 

It seems strange that a block has to opt in, rather than opt out, but there was no intention here - it just wasn't something we were aware of, and doesn't seem to be mentioned anywhere in the Gutenberg handbook as a thing that needs to be done.

**Comment by johngodley** [comment]
I've added a note in the Gutenberg docs so that people using inner blocks are aware that `excerpt_allowed_wrapper_blocks` may be needed. I'm sure a lot of blocks don't do this.

https://github.com/WordPress/gutenberg/pull/36405

**Comment by supernovia** [comment]
Thank you!
