### ISSUE TITLE
Layout Grid does not respect Group constraints

### ISSUE THREAD

**Issue by zaguiini** [Automattic/block-experiments#249]
## Description

When wrapping the Layout Grid with a Group so you can set layout constraints, the changes are not applied.

## Steps to reproduce

1. Insert Layout Grid on the page;
2. Wrap it within a Group;
3. Add Group layout constraints (e.g. column 500px wide 500px);
4. Save.

Check that the layout grid is still occupying the full width even though it was explicitly wrapped in a Group.

## Screenshots

![image](https://user-images.githubusercontent.com/26530524/143097794-4ee7bf0d-f7e3-4c91-bad0-d445888a44e0.png)

![image](https://user-images.githubusercontent.com/26530524/143097824-662a38b7-3587-4873-87cb-c50f33593543.png)

![image](https://user-images.githubusercontent.com/26530524/143097852-7c18cc0a-2f48-4b42-9ac3-afea07f7fa82.png)

**Comment by jasmussen** [comment]
Thanks for the ticket. I can't reproduce this, the layout grid does inherit the constraints set on the parent group:
<img width="1061" alt="Screenshot 2021-12-17 at 09 39 29" src="https://user-images.githubusercontent.com/1204802/146515126-86fabf28-ad73-4440-bf1c-d726a3ec9320.png">

A small preface:

- When the group sets content and wide constraints, those constraints apply to the content inside (no position set) and the wide position.
- By default, the layout grid when inserted is set to full-wide. Full-wide items inside a group _should_ be the full width of the group, but no bigger.

Is it possible you tested with a full-wide layout grid inside a full-wide group?

**Comment by zaguiini** [comment]
Sorry, I'm still able to reproduce the problems. My environment:
- Site Editor;
- Gutenberg `trunk`;
- Layout Grid `trunk`;
- WordPress 5.9.

This is my template:

```html
<!-- wp:group {"align":"full","layout":{"inherit":false,"contentSize":"70%"}} -->
<div class="wp-block-group alignfull"><!-- wp:paragraph -->
<p>Hey</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","layout":{"inherit":false,"contentSize":"70%"}} -->
<div class="wp-block-group alignfull"><!-- wp:jetpack/layout-grid {"column1DesktopSpan":6,"column1TabletSpan":4,"column1MobileSpan":4,"column2DesktopSpan":6,"column2TabletSpan":4,"column2MobileSpan":4} -->
<div class="wp-block-jetpack-layout-grid alignfull column1-desktop-grid__span-6 column1-desktop-grid__row-1 column2-desktop-grid__span-6 column2-desktop-grid__start-7 column2-desktop-grid__row-1 column1-tablet-grid__span-4 column1-tablet-grid__row-1 column2-tablet-grid__span-4 column2-tablet-grid__start-5 column2-tablet-grid__row-1 column1-mobile-grid__span-4 column1-mobile-grid__row-1 column2-mobile-grid__span-4 column2-mobile-grid__row-2"><!-- wp:jetpack/layout-grid-column -->
<div class="wp-block-jetpack-layout-grid-column wp-block-jetpack-layout-grid__padding-none"><!-- wp:paragraph -->
<p>Test</p>
<!-- /wp:paragraph --></div>
<!-- /wp:jetpack/layout-grid-column -->

<!-- wp:jetpack/layout-grid-column -->
<div class="wp-block-jetpack-layout-grid-column wp-block-jetpack-layout-grid__padding-none"><!-- wp:paragraph -->
<p>Test</p>
<!-- /wp:paragraph --></div>
<!-- /wp:jetpack/layout-grid-column --></div>
<!-- /wp:jetpack/layout-grid --></div>
<!-- /wp:group -->
```

This is what I see when I select the group without Layout Grid:

![image](https://user-images.githubusercontent.com/26530524/146584587-148717a8-c521-48d6-b73c-f18e69461752.png)

And this is what I get when wrapping Layout Grid into a group with the same layout settings:

![image](https://user-images.githubusercontent.com/26530524/146584655-ef86282e-9f49-47a9-975f-bebee00256b9.png)

Final result:

![image](https://user-images.githubusercontent.com/26530524/146584673-3e5e7a2a-9979-40de-b060-d9067f75d562.png)

**Comment by zaguiini** [comment]
> * Full-wide items inside a group _should_ be the full width of the group, but no bigger.

Of course, but shouldn't they respect the margin set by the Group as well?

**Comment by jasmussen** [comment]
Thanks for the followup, I'll take a look when I get a moment. Which theme are you using? Themes often provide styles that affect the rendering of blocks, and in some cases, can be at fault.

**Comment by zaguiini** [comment]
I tried with Quadrat, TT2, and this time it was Blank Canvas 2.

**Comment by jasmussen** [comment]
I'm still seeing this working as intended, insofar as fullwide blocks inside fullwide blocks do not have max-widths applied, those max-widths are reserved for _content_ (no alignment set) and wide alignments:

![layout grid](https://user-images.githubusercontent.com/1204802/146901494-a21b93a6-c898-478e-9919-8a233ad5d571.gif)

In the code sample you gave (thank you!) I'm seeing the fullwide position applied to the layout grid:

<img width="857" alt="Screenshot 2021-12-21 at 09 57 35" src="https://user-images.githubusercontent.com/1204802/146901560-d559fe44-0f71-4c9b-9a6e-5490f6f30066.png">

> but shouldn't they respect the margin set by the Group as well?

Margin isn't officially enabled on the group block yet, but I tried applying a wide padding and border, and that appeared to still correctly scale the layout grid inside:
<img width="1660" alt="Screenshot 2021-12-21 at 10 00 47" src="https://user-images.githubusercontent.com/1204802/146901771-110d2401-a894-4904-9a65-6642093db629.png">

**Comment by zaguiini** [comment]
Sorry for the late response, @jasmussen.

> Margin isn't officially enabled on the group block yet

Isn't CSS `margin` applied when you define constraints to the `Group` block?

But I see, it looks like we have an option to have it full-width, regardless of the parent constraints. It's not intuitive, though. I wouldn't expect the child to tell the parent how to behave 🤔  Can we do something about it?

**Comment by jasmussen** [comment]
> Isn't CSS margin applied when you define constraints to the Group block?

Can you help me understand this one? Padding and block spacing (gap between blocks inside) is supported on the group block:
<img width="1392" alt="Screenshot 2022-01-10 at 08 42 43" src="https://user-images.githubusercontent.com/1204802/148732252-7a3c1b91-c06f-4d23-8609-c6a9ea301450.png">

> But I see, it looks like we have an option to have it full-width, regardless of the parent constraints. It's not intuitive, though. I wouldn't expect the child to tell the parent how to behave 🤔 Can we do something about it?

I think I understand what you're saying: if the layout grid block is set to be full-wide by default, it's confusing that doesn't work inside a group that isn't fullwide. Is that right?

Here's a GIF of how it's working in the latest version of the editor:
![grid](https://user-images.githubusercontent.com/1204802/148732701-bd7d69c4-66ac-4241-bbf1-a30ba4b85fb0.gif)

That is, unless the group block defines a "layout" (in the GIF I choose "inherit default layout", but I could also specify contnent and wide widths inside), then wide and fullwide options are not available as options for blocks inside. 

For consistency, it seems like the best path forward here is to revisit the decision to make the layout grid be full-wide by default, and toggle that off. What do you think?

**Comment by zaguiini** [comment]
>I think I understand what you're saying: if the layout grid block is set to be full-wide by default, it's confusing that doesn't work inside a group that isn't fullwide. Is that right?

Exactly!

> What do you think?

Looks like it! How could we coordinate that change?

**Comment by jasmussen** [comment]
I'll see if I can make a PR.

**Comment by jasmussen** [comment]
Created a PR in #258.
