### ISSUE TITLE
Layout Grid: column vertical alignment doesn't work in preview

### ISSUE THREAD

**Issue by zaguiini** [Automattic/block-experiments#250]
It works fine on the live site. However, preview always displays the column's contents at the top, vertically speaking.

| Preview | Live site |
| -------- | -------- |
| ![image](https://user-images.githubusercontent.com/26530524/145629529-f4977ca3-f98d-4b77-aa90-7209ba90b0df.png) | ![image](https://user-images.githubusercontent.com/26530524/145629565-f2d16b6c-26a2-43a1-a926-08e7abdee73a.png) |

Notice how the center alignment option is selected in the Column block.

**Comment by jasmussen** [comment]
Thanks for the ticket! Do you have additional steps to reproduce? I'm seeing the correct alignment both in the editor and the frontend:
<img width="1206" alt="Screenshot 2021-12-13 at 10 55 17" src="https://user-images.githubusercontent.com/1204802/145790642-72a1cd8e-32dd-4896-869b-636da9c30019.png">

**Comment by zaguiini** [comment]
Interesting. It might be Dotcom specific, then?

Or, it might be related to possibly outdated block pattern markup? I'll need to check.

**Comment by jasmussen** [comment]
In a quick test, it worked fine. Which theme are you testing with?

**Comment by zaguiini** [comment]
Quadrat. How are you testing it?

My instructions:

1. Add `Layout Grid`;
2. Add `Image` to the first column;
3. Add `Paragraph` to the second column;
4. Try to vertically align the second column.

I'll try on core WP again.

**Comment by jasmussen** [comment]
Testing with the same steps:
<img width="1841" alt="Screenshot 2021-12-13 at 18 33 20" src="https://user-images.githubusercontent.com/1204802/145860550-d36f5259-de18-4686-991d-6a1e3e1febc1.png">

**Comment by zaguiini** [comment]
LOL, I'm questioning my sanity at this point 😄 

This is what I get on Core WP:

![image](https://user-images.githubusercontent.com/26530524/145861056-076b4ca3-f2d2-4115-ac3a-9f9ca1a58005.png)

**Comment by jasmussen** [comment]
This is the quadrat theme customized white? I'll take a look again. Theme and other plugins are important too, as sometimes their css can bleed into other blocks.

**Comment by zaguiini** [comment]
This time it was TT2, not Quadrat.

**Comment by jasmussen** [comment]
I can reproduce in the site editor, not in the post editor. Taking a look.

**Comment by jasmussen** [comment]
Very curious. The markup and CSS appears to be mostly the same, but I can indeed reproduce the issue here. I'll take a stab at fixing this tomorrow. Thanks for the report!

**Comment by zaguiini** [comment]
Oh, so that was the missing bit! My bad, I'm so used at working on the FSE that I forgot there's more than that 😓

**Comment by jasmussen** [comment]
There really shouldn't be, but for the near future, the site editor is iframed and the post editor is not. I would hope we can iframe both, so the target should be more uniform.
