### ISSUE TITLE
Layout Grid: Option to remove gutters on outside

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/block-experiments#29]
Having gutters on outside works most of the time, but sometimes, it'd be handy to have an option to remove the gutters on the outside.

For example, when a Layout Grid block is inside of a Group block with a background color, it ends up having extra side paddings because of the paddings from the Group block.

Also, you might want the images in the columns to stick to the browser edge...

What do you think?

![Artboard](https://user-images.githubusercontent.com/908665/74389980-d1c79400-4df7-11ea-8748-fb71df0d0193.png)

**Comment by johngodley** [comment]
Yep this sounds like a good idea. Linking to #30 as they can both probably be done at the same time.

**Comment by alaczek** [comment]
The gutter issues keep popping up when creating block patterns, so sounds like it would be an impactful change. Could we somehow expedite the work on this one?

Few more use cases:
https://github.com/Automattic/blockpatterns/issues/15
https://github.com/Automattic/blockpatterns/issues/14
https://github.com/Automattic/blockpatterns/issues/3

**Comment by johngodley** [comment]
I'm going to look at this next.

**Comment by johngodley** [comment]
This will probably get deployed early next week. I'll drop a note here when it's in production.

**Comment by iamtakashi** [comment]
That is awesome. Thank you both for working on the fix!

**Comment by johngodley** [comment]
There's a Phabricator diff up for review at D39993, and a standalone plugin zip here [jetpack-layout-grid.zip](https://github.com/Automattic/block-experiments/files/4298530/jetpack-layout-grid.zip). It'd be great if you you could give it a bit of a test and see if:

- Existing grid blocks don't break
- The new features (end gutter option, and gutter size) do what you need

There's also a small fix for IE11. I don't know where compatibility figures in the theme designs, but the grid should look a bit better (but still not great).

**Comment by johngodley** [comment]
Ok, this is merged now
