### ISSUE TITLE
Layout Block: grids misaligned

### ISSUE THREAD

**Issue by akirk** [Automattic/block-experiments#3]
When testing this I was wondering if the blue line should be on the dotted line of the column?

<img width="1331" alt="Screenshot 2019-12-06 at 14 28 44" src="https://user-images.githubusercontent.com/203408/70326417-d8082580-1834-11ea-9a80-afc692f0c44c.png">

**Comment by johngodley** [comment]
I can't remember if this is intentional or not, so pinging @jasmussen

**Comment by jasmussen** [comment]
Can you share a screenshot that features text instead of the generic appender? I think the appender adds margin that is imprecise, and may be fixed upstream.

**Comment by johngodley** [comment]
Yep, confirming this is fixed with Gutenberg 7.1

![Edit_Page___Pages_by_WordPress_com](https://user-images.githubusercontent.com/1277682/70700769-2731d880-1cc3-11ea-9976-ccfb5a458ec1.jpg)

For older Gutenbergs the misalignment is still usable, so I'll mark this as resolved.

**Comment by akirk** [comment]
Thanks for confirming this will be fixed!
