### ISSUE TITLE
Layout Grid: Setting options for gutters

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/block-experiments#30]
Currently, the gutter is fixed to 24px, but It'd be great if the user could increase/decrease the gutter size. If the setting allows them to set to `0`, they could even have a gutterless grid that would be handy for media-oriented page layouts.

**Comment by ianstewart** [comment]
Do you have a visual example for this one?

**Comment by iamtakashi** [comment]
For a basic example:

![Screenshot 2020-02-18 at 17 06 33](https://user-images.githubusercontent.com/908665/74759828-4fb0f280-5271-11ea-9433-735c4841507c.png)
