### ISSUE TITLE
Block Experiments

### ISSUE THREAD

**Issue by nickhamze** [Automattic/block-experiments#32]
I hope you don't mind me posting here. I just wanted to pop in a and start a conversation. I really like what you all are doing here. I'm doing something sorta similar over at https://profiles.wordpress.org/sortabrilliant/#content-plugins . Creating blocks that no one has seen before. I've noticed that you've released a few things and are having as hard of a time as me getting installs. 

I was wondering if you had any plans to get more installs. Making things is fun and I'll keep doing it but it would be really helpful if I could get more installs as I'm making things blind now and I'll love to get real user's feedback. I'm constantly surprised how people end up using things I make.

I thought maybe since we are both in the block R&D business we could help each other out.

**Comment by mkaz** [comment]
@nickhamze I missed this, so sorry for the delayed response. The block directory will hopefully be a good solution for block discovery, and thus will help people finding new blocks they might be interested in.

So at the moment, we're not overly concerned about install numbers and usage, our main goal is trying to learn and build extensions on Gutenberg, this helps us discover issues and iterate on the core platform.
