### ISSUE TITLE
Layout Grid: Can't Edit block in new Wordpress editor anymore

### ISSUE THREAD

**Issue by mar-ii-a** [Automattic/block-experiments#323]
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/84680955/234134078-d467f245-3a7b-4417-80ab-bfea7a7cfbb2.png">

I'm now unable to edit anything where I have used this block. I've tried on chrome and safari multiple times, but it shows me unable to use the editor.

**Comment by johngodley** [comment]
This should now work in the site editor in 1.8.3
