### ISSUE TITLE
Layout Grid Block broken on WP 6.2

### ISSUE THREAD

**Issue by ooksanen** [Automattic/block-experiments#325]
As noted in #323, Layout Grid Block doesn't work properly on WP 6.2, and possibly on some earlier versions too. Seems to work ok in post editor for me, but breaks at least in template parts. Do you have any plans on updating these blocks (@jasmussen?) or are these considered abandoned?

IMO the Layout Grid is really useful and something I'd definitely like to see developed further, or at least kept up to date, and possibly even merged to Gutenberg core at some stage, but if there's no one working on this, I might have to fork it to a new plugin. At the moment it's unfortunately not suitable for real world use.

**Comment by johngodley** [comment]
It should now work in the site editor in 1.8.3
