### ISSUE TITLE
Explore Zoom-cropping

### ISSUE THREAD

**Issue by jasmussen** [Automattic/block-experiments#33]
In the Image Tools efforts that are currently [proposed for the core project](https://github.com/WordPress/gutenberg/issues/13748#issuecomment-574903126), a traditional cropping interface exists, complete with marching ants and resize handles:

![72490878-44c7f580-37cd-11ea-9108-2e330c7d22d5](https://user-images.githubusercontent.com/1204802/75135000-5f509100-56e0-11ea-9e7e-55c7d61388aa.gif)

It works like this:

- Click crop
- Resize and position
- Click apply
- The smaller, cropped image, now replaces the old

This interface is a classic mouse-first interface that requires some dexterity to manipulate, but is otherwise good. One downside is that you can crop the image so small that it won't even fit the UI. Another downside is that the resolution of the crop is dependant on the viewport width, i.e. you might have a giant 1600px image that is scaled down to fit the Image block which may only be 720px wide. The cropping then happens based on that scaled down version, making any crop smaller still. 

**Zoom-cropping**, for lack of a better term, puts emphasis on keeping the block dimensions the same before or after the crop. Instead of resizing handles, you zoom and pan the image to apply the crop.

It is common on mobile, and can be combined with resize handles. Here's how it works on Android:

https://cloudup.com/c_Tpqjs9NBM

There are a couple of benefits to this interface:

1. With its heavy reliance on zoom as the default interface, it's less fiddly especially on mobile.
2. It can work for blocks that require "soft-crops", i.e. CSS crop. This could be videos for example.
3. It _can_ be combined with the resize handles.

**Comment by ajlende** [comment]
The Rich Image block has moved to the Gutenberg [Image Block](https://github.com/WordPress/gutenberg/tree/master/packages/block-library/src/image) where zoom cropping is implemented with [react-easy-crop](https://github.com/ricardo-ch/react-easy-crop).
