### ISSUE TITLE
Starscape slider crops on right

### ISSUE THREAD

**Issue by johngodley** [Automattic/block-experiments#41]
The gradient slider in the starscape block crops the right circle:

![Edit_Post_‹_Latest_—_WordPress](https://user-images.githubusercontent.com/1277682/76070784-03fa8a80-5f8d-11ea-8532-85279485d5a6.jpg)

Tested in Gutenberg 6.5 & Chrome.

**Comment by ajlende** [comment]
Accidentally opened a duplicate. This will be fixed by https://github.com/WordPress/gutenberg/pull/20670
