### ISSUE TITLE
Layout grid: no gutter crops right block border

### ISSUE THREAD

**Issue by johngodley** [Automattic/block-experiments#49]
A grid with no gutter crops the right side of the block:

<img width="152" alt="Edit_Post_‹_Latest_—_WordPress" src="https://user-images.githubusercontent.com/1277682/76321995-b195d280-62da-11ea-8c9d-a880d6209927.png">

We should add a small gutter when showing in the editor.

**Comment by jasmussen** [comment]
Dependant on https://github.com/WordPress/gutenberg/pull/21498, I believe.

Otherwise, @johngodley can you confirm whether this was fixed by the V2?

**Comment by johngodley** [comment]
Yes, this was fixed as part of #71
