### ISSUE TITLE
Layout Grid: Vertical alignment option

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/block-experiments#52]
It'd be great if we allow controlling vertical alignments like the column block from core.

I wanted to make a block pattern like this:
![tiled-gallery](https://user-images.githubusercontent.com/908665/76649992-a2708800-6559-11ea-9e4f-33f86aff3e93.png)

But at the moment:
![tiled-gallery-2](https://user-images.githubusercontent.com/908665/76650112-d8157100-6559-11ea-9cd9-766a14d5a4a1.png)

Layout Grid is so much better than the one from core, and I'd love to not give up all the advantages just because of the lack of vertical alignment :)

cc @ianstewart @alaczek

**Comment by iamtakashi** [comment]
In addition to top, middle, and bottom, it might be handy to have an option for an equivalent to flexbox's `space-between` for when there is more than one element in a column.

![Pattern 4](https://user-images.githubusercontent.com/908665/76863422-5eca9680-6857-11ea-8b2a-201d0493897e.png)

**Comment by johngodley** [comment]
I've started exploring this in #100

>  it might be handy to have an option for an equivalent to flexbox's space-between 

Gutenberg provides the vertical alignment control, so a `space-between` would need to be added there and it would then be available to all blocks.
