### ISSUE TITLE
Layout Grid: `front.css` appears at the bottom of the HTML doc.

### ISSUE THREAD

**Issue by allancole** [Automattic/block-experiments#64]
I’m not sure if this is intentional but while testing the Layout Grid plugin I noticed that the frontend stylesheet gets loaded into the footer of the doc instead of in `wp_head()` where I’d typically expect a stylesheet to appear. This isn’t a problem on its own, however if I wanted to override the stylesheet in a theme, I either have to load my overriding styles in the footer as well or use `!important` in the CSS itself, both of which aren’t ideal for best practices. 

Looking at the following line, it seems the stylesheet _should_ be enqueued in `wp_head`:

https://github.com/Automattic/block-experiments/blob/3ba0903b9fd69647874c480a014f23dfb0b3cfb9/blocks/layout-grid/index.php#L19-L26

But as you can see in this screenshot it actually appears at the end of the doc: 

![image](https://user-images.githubusercontent.com/709581/78049996-b71a9180-7349-11ea-9413-53215650adca.png)

With themes, we usually enqueue stylesheets into the header on the frontend with `'wp_enqueue_scripts'` ie:
```
add_action( 'wp_enqueue_scripts', function() {…});
```

Maybe the same or similar could be used to solve this?

**Comment by johngodley** [comment]
Thanks! I've put the fix into https://github.com/Automattic/block-experiments/pull/79.

It doesn't seem to negatively affect anything else, but when it comes to deploying I'll loop you in to the diff so we can make sure it doesn't break anything.
