### ISSUE TITLE
Layout grid: look at classes added when adjusting columns

### ISSUE THREAD

**Issue by johngodley** [Automattic/block-experiments#65]
Look at the problem reported in Calypso:

https://github.com/Automattic/wp-calypso/issues/40462

**Comment by jasmussen** [comment]
Closed the wp calypso ticket, so closing this one!

**Comment by johngodley** [comment]
This only occurs when you have a grid with non-default start/spans. If you then change the number of columns the block is correctly updating the classes, but Gutenberg is then adding some additional classes after saving.

Still digging into why this would happen.
