### ISSUE TITLE
Selecting an image sets focus on caption

### ISSUE THREAD

**Issue by jasmussen** [Automattic/block-experiments#68]
This issue appears to be something the block-experiments plugin does, and not the master branch of Gutenberg. 

Compare the master branch with the master branch and this plugin active:

- Insert an image. Add a caption or don't. 
- Unselect the image.
- Click the image to select it.

Note how when this plugin is active, the caption gets focus, not the image.

![caption focus](https://user-images.githubusercontent.com/1204802/78867909-35f68500-7a42-11ea-83ab-566f8a16b1ba.gif)

**Comment by ajlende** [comment]
The Rich Image block has moved to the Gutenberg [Image Block](https://github.com/WordPress/gutenberg/tree/master/packages/block-library/src/image).
