### ISSUE TITLE
Image blocks are out of date with latest master

### ISSUE THREAD

**Issue by jasmussen** [Automattic/block-experiments#69]
The rich image tools in this plugin have become out of date with the image block markup shipping in the latest version of the plugin. A "Lighter DOM" effort there has been merged, which reduces the Image block in the editor to the same markup that exists on the frontend. 

This version of the plugin adds an extra div, which breaks the layout. 

As we are looking at donating the efforts to the core project itself, perhaps we should disable the older version of Image tools that exist in this plugin for the time being?

**Comment by jasmussen** [comment]
This one possibly also fixes #68. CC: @johngodley

**Comment by ajlende** [comment]
The Rich Image block has moved to the Gutenberg [Image Block](https://github.com/WordPress/gutenberg/tree/master/packages/block-library/src/image).
