### ISSUE TITLE
Layout Grid: Grid not reserving the available width

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/block-experiments#82]
It's likely this is happening with the recent update, but the grid is no-longer reserving the width specified in the setting. This is the content that I realised this.

On WP.com currently, and it used to look like this. The grid inside a group block uses all the space available.
<img width="2611" alt="Screenshot 2020-04-24 at 20 53 32" src="https://user-images.githubusercontent.com/908665/80251559-b685ca00-866d-11ea-89f8-f142880c09d3.png">

But in my local install where I cloned this repo, it looks like this now. The grid is a lot narrow.
<img width="2611" alt="Screenshot 2020-04-24 at 20 53 42" src="https://user-images.githubusercontent.com/908665/80251577-bede0500-866d-11ea-9f4c-9c539cf7b10f.png">

This is a test content that I copied from where I noticed this. Feel free to use it as a test content.

I hope I'm not doing anything dumb, but could you try to replicate the issue? Thanks in advance!

```
<!-- wp:group {"align":"full","style":{"color":{"background":"#fddeda"}}} -->
<div class="wp-block-group alignfull has-background" style="background-color:#fddeda"><div class="wp-block-group__inner-container"><!-- wp:spacer {"height":60} -->
<div style="height:60px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:jetpack/layout-grid {"column1DesktopSpan":2,"column1DesktopOffset":1,"column1TabletSpan":4,"column1MobileSpan":4,"column2DesktopSpan":4,"column2TabletSpan":4,"column2MobileSpan":4,"column3DesktopSpan":4,"column3TabletSpan":8,"column3MobileSpan":4,"column4DesktopOffset":1,"className":"column1-desktop-grid__span-2 column1-desktop-grid__start-2 column1-desktop-grid__row-1 column2-desktop-grid__span-4 column2-desktop-grid__start-4 column2-desktop-grid__row-1 column3-desktop-grid__span-4 column3-desktop-grid__start-8 column3-desktop-grid__row-1 column1-tablet-grid__span-4 column1-tablet-grid__row-1 column2-tablet-grid__span-4 column2-tablet-grid__start-5 column2-tablet-grid__row-1 column3-tablet-grid__span-8 column3-tablet-grid__row-2 column1-mobile-grid__span-4 column1-mobile-grid__row-1 column2-mobile-grid__span-4 column2-mobile-grid__row-2 column3-mobile-grid__span-4 column3-mobile-grid__row-3"} -->
<div class="wp-block-jetpack-layout-grid alignfull column1-desktop-grid__span-2 column1-desktop-grid__start-2 column1-desktop-grid__row-1 column2-desktop-grid__span-4 column2-desktop-grid__start-4 column2-desktop-grid__row-1 column3-desktop-grid__span-4 column3-desktop-grid__start-8 column3-desktop-grid__row-1 column1-tablet-grid__span-4 column1-tablet-grid__row-1 column2-tablet-grid__span-4 column2-tablet-grid__start-5 column2-tablet-grid__row-1 column3-tablet-grid__span-8 column3-tablet-grid__row-2 column1-mobile-grid__span-4 column1-mobile-grid__row-1 column2-mobile-grid__span-4 column2-mobile-grid__row-2 column3-mobile-grid__span-4 column3-mobile-grid__row-3"><!-- wp:jetpack/layout-grid-column -->
<div class="wp-block-jetpack-layout-grid-column wp-block-jetpack-layout-grid__padding-none"><!-- wp:heading {"level":5} -->
<h5>Follow Me</h5>
<!-- /wp:heading --></div>
<!-- /wp:jetpack/layout-grid-column -->

<!-- wp:jetpack/layout-grid-column -->
<div class="wp-block-jetpack-layout-grid-column wp-block-jetpack-layout-grid__padding-none"><!-- wp:paragraph -->
<p>Get new content delivered directly to your inbox.</p>
<!-- /wp:paragraph -->

<!-- wp:jetpack/subscriptions -->
<div class="wp-block-jetpack-subscriptions">[jetpack_subscription_form show_only_email_and_button="true" custom_background_button_color="undefined" custom_text_button_color="undefined" submit_button_text="Subscribe" submit_button_classes="undefined" show_subscribers_total="false" ]</div>
<!-- /wp:jetpack/subscriptions --></div>
<!-- /wp:jetpack/layout-grid-column -->

<!-- wp:jetpack/layout-grid-column -->
<div class="wp-block-jetpack-layout-grid-column wp-block-jetpack-layout-grid__padding-none"><!-- wp:social-links -->
<ul class="wp-block-social-links"><!-- wp:social-link {"url":"https://wordpress.org","service":"wordpress"} /-->

<!-- wp:social-link {"url":"https://facebook.com","service":"facebook"} /-->

<!-- wp:social-link {"url":"https://twitter.com","service":"twitter"} /-->

<!-- wp:social-link {"url":"https://instagrame.com","service":"instagram"} /-->

<!-- wp:social-link {"url":"https://linkedin.com","service":"linkedin"} /-->

<!-- wp:social-link {"url":"https://youtube.com","service":"youtube"} /--></ul>
<!-- /wp:social-links --></div>
<!-- /wp:jetpack/layout-grid-column --></div>
<!-- /wp:jetpack/layout-grid -->

<!-- wp:spacer {"height":60} -->
<div style="height:60px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer --></div></div>
<!-- /wp:group -->
```

**Comment by johngodley** [comment]
That HTML works fine for. Is your local site using a theme that supports full width? If full width isn't supported then you'll get the effect you've shown above. If it does support full width, is there a way to test this?

**Comment by iamtakashi** [comment]
I've tested with themes like Twenty Twenty and Twenty Nineteen that support full width.

I could have been clearer, and the issue is happening in the Editor only, and the grid appears as expected on the front of the site.

I hope the following screenshots illustrate better the issue that I'm seeing. The page has two identical Layout Grid blocks that have three-column. 

It seems like the column width depends on the content inside instead of reserving the width based on the units allocated to itself. If you can't replicate the issue, please let me know.

**Editor**
![Screenshot 2020-04-27 at 15 14 03](https://user-images.githubusercontent.com/908665/80382328-1365c800-889a-11ea-9e65-09f609bce929.png)

**Front of the site**
![Screenshot 2020-04-27 at 15 14 21](https://user-images.githubusercontent.com/908665/80382360-1d87c680-889a-11ea-8660-95609325ebee.png)


```
<!-- wp:jetpack/layout-grid {"column1DesktopSpan":4,"column1TabletSpan":4,"column1MobileSpan":4,"column2DesktopSpan":4,"column2TabletSpan":4,"column2MobileSpan":4,"column3DesktopSpan":4,"column3TabletSpan":8,"column3MobileSpan":4,"className":"column1-desktop-grid__span-4 column1-desktop-grid__row-1 column2-desktop-grid__span-4 column2-desktop-grid__start-5 column2-desktop-grid__row-1 column3-desktop-grid__span-4 column3-desktop-grid__start-9 column3-desktop-grid__row-1 column1-tablet-grid__span-4 column1-tablet-grid__row-1 column2-tablet-grid__span-4 column2-tablet-grid__start-5 column2-tablet-grid__row-1 column3-tablet-grid__span-8 column3-tablet-grid__row-2 column1-mobile-grid__span-4 column1-mobile-grid__row-1 column2-mobile-grid__span-4 column2-mobile-grid__row-2 column3-mobile-grid__span-4 column3-mobile-grid__row-3"} -->
<div class="wp-block-jetpack-layout-grid alignfull column1-desktop-grid__span-4 column1-desktop-grid__row-1 column2-desktop-grid__span-4 column2-desktop-grid__start-5 column2-desktop-grid__row-1 column3-desktop-grid__span-4 column3-desktop-grid__start-9 column3-desktop-grid__row-1 column1-tablet-grid__span-4 column1-tablet-grid__row-1 column2-tablet-grid__span-4 column2-tablet-grid__start-5 column2-tablet-grid__row-1 column3-tablet-grid__span-8 column3-tablet-grid__row-2 column1-mobile-grid__span-4 column1-mobile-grid__row-1 column2-mobile-grid__span-4 column2-mobile-grid__row-2 column3-mobile-grid__span-4 column3-mobile-grid__row-3"><!-- wp:jetpack/layout-grid-column -->
<div class="wp-block-jetpack-layout-grid-column wp-block-jetpack-layout-grid__padding-none"><!-- wp:image {"sizeSlug":"large"} -->
<figure class="wp-block-image size-large"><img src="https://upload.wikimedia.org/wikipedia/commons/6/6e/Monasterio_Khor_Virap%2C_Armenia%2C_2016-10-01%2C_DD_25.jpg" alt=""/></figure>
<!-- /wp:image --></div>
<!-- /wp:jetpack/layout-grid-column -->

<!-- wp:jetpack/layout-grid-column -->
<div class="wp-block-jetpack-layout-grid-column wp-block-jetpack-layout-grid__padding-none"><!-- wp:image {"sizeSlug":"large"} -->
<figure class="wp-block-image size-large"><img src="https://upload.wikimedia.org/wikipedia/commons/6/6e/Monasterio_Khor_Virap%2C_Armenia%2C_2016-10-01%2C_DD_25.jpg" alt=""/></figure>
<!-- /wp:image --></div>
<!-- /wp:jetpack/layout-grid-column -->

<!-- wp:jetpack/layout-grid-column -->
<div class="wp-block-jetpack-layout-grid-column wp-block-jetpack-layout-grid__padding-none"><!-- wp:image {"sizeSlug":"large"} -->
<figure class="wp-block-image size-large"><img src="https://upload.wikimedia.org/wikipedia/commons/6/6e/Monasterio_Khor_Virap%2C_Armenia%2C_2016-10-01%2C_DD_25.jpg" alt=""/></figure>
<!-- /wp:image --></div>
<!-- /wp:jetpack/layout-grid-column --></div>
<!-- /wp:jetpack/layout-grid -->

<!-- wp:jetpack/layout-grid {"column1DesktopSpan":4,"column1TabletSpan":4,"column1MobileSpan":4,"column2DesktopSpan":4,"column2TabletSpan":4,"column2MobileSpan":4,"column3DesktopSpan":4,"column3TabletSpan":8,"column3MobileSpan":4,"className":"column1-desktop-grid__span-4 column1-desktop-grid__row-1 column2-desktop-grid__span-4 column2-desktop-grid__start-5 column2-desktop-grid__row-1 column3-desktop-grid__span-4 column3-desktop-grid__start-9 column3-desktop-grid__row-1 column1-tablet-grid__span-4 column1-tablet-grid__row-1 column2-tablet-grid__span-4 column2-tablet-grid__start-5 column2-tablet-grid__row-1 column3-tablet-grid__span-8 column3-tablet-grid__row-2 column1-mobile-grid__span-4 column1-mobile-grid__row-1 column2-mobile-grid__span-4 column2-mobile-grid__row-2 column3-mobile-grid__span-4 column3-mobile-grid__row-3"} -->
<div class="wp-block-jetpack-layout-grid alignfull column1-desktop-grid__span-4 column1-desktop-grid__row-1 column2-desktop-grid__span-4 column2-desktop-grid__start-5 column2-desktop-grid__row-1 column3-desktop-grid__span-4 column3-desktop-grid__start-9 column3-desktop-grid__row-1 column1-tablet-grid__span-4 column1-tablet-grid__row-1 column2-tablet-grid__span-4 column2-tablet-grid__start-5 column2-tablet-grid__row-1 column3-tablet-grid__span-8 column3-tablet-grid__row-2 column1-mobile-grid__span-4 column1-mobile-grid__row-1 column2-mobile-grid__span-4 column2-mobile-grid__row-2 column3-mobile-grid__span-4 column3-mobile-grid__row-3"><!-- wp:jetpack/layout-grid-column -->
<div class="wp-block-jetpack-layout-grid-column wp-block-jetpack-layout-grid__padding-none"><!-- wp:heading -->
<h2>First Column</h2>
<!-- /wp:heading --></div>
<!-- /wp:jetpack/layout-grid-column -->

<!-- wp:jetpack/layout-grid-column -->
<div class="wp-block-jetpack-layout-grid-column wp-block-jetpack-layout-grid__padding-none"><!-- wp:heading -->
<h2>Second Column</h2>
<!-- /wp:heading --></div>
<!-- /wp:jetpack/layout-grid-column -->

<!-- wp:jetpack/layout-grid-column -->
<div class="wp-block-jetpack-layout-grid-column wp-block-jetpack-layout-grid__padding-none"><!-- wp:heading -->
<h2>Third Column</h2>
<!-- /wp:heading --></div>
<!-- /wp:jetpack/layout-grid-column --></div>
<!-- /wp:jetpack/layout-grid -->
```

**Comment by johngodley** [comment]
Sorry, I'm still not seeing the problem! Using your above HTML here's how it looks on 2020 on a local install:

![image](https://user-images.githubusercontent.com/1277682/80488511-5ab18e80-8956-11ea-9d91-3be289ca280e.png)

And on WP.com on another theme:

![image](https://user-images.githubusercontent.com/1277682/80488551-6bfa9b00-8956-11ea-84e4-cbadeab939a0.png)

Do you have anything else locally that could be affecting things? Is it the latest version of the plugin?

**Comment by iamtakashi** [comment]
Thanks for trying to replicate! It seems like my local install has something missing...

> Is it the latest version of the plugin?
By cloning this repo, I can assume I have the latest version of the plugin, correct?

**Comment by johngodley** [comment]
Kind of, although this repo is more for developing and you'd need to build the plugin. If all you want is the layout grid itself you can download it here:

https://wordpress.org/plugins/layout-grid/

**Comment by iamtakashi** [comment]
> you'd need to build the plugin

Yes, I have built the plugin. But, I don't see this issue with the stand-alone plugin. So no need to be alarmed :)

By looking at closely the markup and the css with the version in this repo, it seems like the removal of this style causing the issue that I'm seeing.

```
[data-type="jetpack/layout-grid"][data-align="full"] > div {
    width: 100%;
}
```

This was replaced with the following in #71, but I don't see the css class `.is-block-content` in the markup currently.

```
[data-type="jetpack/layout-grid"][data-align="full"] .is-block-content {
   width: 100%;
}
```

In this repo (not aligning)
<img width="1364" alt="Screenshot 2020-04-28 at 14 55 59" src="https://user-images.githubusercontent.com/908665/80495932-70c44c80-8960-11ea-93d4-f42b8261ac4f.png">

Stand-alone version (aligned as expected)
<img width="1364" alt="Screenshot 2020-04-28 at 14 56 03" src="https://user-images.githubusercontent.com/908665/80496082-9c473700-8960-11ea-9bbb-8c319fbe72d9.png">

I can't replicate this in WP.com or with the stand-alone version, so I assume this change was for something that's coming soon? ("V2" makes me think that way) Am I jumping the gun?

Thanks for taking time on this, I'm perfectly ok with the stand-alone plugin.

**Comment by johngodley** [comment]
What version of WP are you using? The plugin is being targeted at 5.4, and `.is-block-content` is part of that. The current plugin doesn't contain these changes yet.

**Comment by iamtakashi** [comment]
`wp-admin/about.php` says, I have 5.4.

**Comment by johngodley** [comment]
Are you using Gutenberg as a plugin and maybe have an older version?

Yes, the class seems to be a child element of the grid block:

![image](https://user-images.githubusercontent.com/1277682/80508924-92c5cb00-8970-11ea-9faf-d2c7e25ea7aa.png)

@jasmussen may have some thoughts about why it's not working in your local install

**Comment by jasmussen** [comment]
I think we might need to add that rule back, this one: https://github.com/Automattic/block-experiments/issues/82#issuecomment-620631771. `is-block-content` is newish. And okay, I just tested now — that rule is present in 5.4 even without the plugin, so I think I need to be able to reproduce this. Taking a look and returning.

**Comment by jasmussen** [comment]
Okay so I think the align-center rule I noted in https://github.com/Automattic/block-experiments/pull/83#issuecomment-620704816 may fix this. Let me try a separate PR for this.

**Comment by iamtakashi** [comment]
Thank you all for your help. If I deactivate Gutenberg plugin (V8.0.0-rc.1), `is-block-content` gets added and all works fine. But activating the plugin removes the class for me. Strange...

**Comment by jasmussen** [comment]
> Thank you all for your help. If I deactivate Gutenberg plugin (V8.0.0-rc.1), is-block-content gets added and all works fine. But activating the plugin removes the class for me.

**Comment by jasmussen** [comment]
To be clear I'm not seeing your issue with or without that rule, but if it's causing issues, might as well keep it!

**Comment by iamtakashi** [comment]
> I'm not seeing your issue with or without that rule

Instead of a paragraph, can you try something like a letter which is very short?

Anyway, I'll test the PR!
