### ISSUE TITLE
Layout Grid: Allow gridlines to be toggled

### ISSUE THREAD

**Issue by shaunandrews** [Automattic/block-experiments#89]
![image (1)](https://user-images.githubusercontent.com/191598/81209544-b1464a80-8f9e-11ea-96b5-0998ab469fc6.png)

It can be pretty easy to get to a point where the gridlines are more distracting than helpful. For people creating patterns or themes, the Grid Layout guides are likely helpful.

However, for the end-user who is adding and using these patterns, the guides are somewhat cryptic (notice they don't line up to the actual columns) and distracting. At first glance, the guides appear to be a rendering bug and its not obvious when/why they appear — this all leads to confusion when previewing the output on the site's frontend.

I'd be nice to have a way to toggle the guides on an off, and for WPcom specifically, it might be nice to be able to turn them off by default.

**Comment by johngodley** [comment]
I don't recall the grid lines being visible in this way before, but I may have forgotten.

@jasmussen was this added in the last version? Having an option doesn't sound great. Maybe we can show them only when resizing?

**Comment by jasmussen** [comment]
The grid lines were redesigned recently to be solids instead of lines. First thing to try would be to not show the gridlines unless the grid block itself, or a grid column is selected, i.e. not also when `has-child-selected`.

**Comment by pablohoneyhoney** [comment]
Agree with @jasmussen 
The fact that they are not behaving correctly yet is not enough to afford toggle or remove them by default.

**Comment by johngodley** [comment]
> First thing to try would be to not show the gridlines unless the grid block itself

I think this is already the case as the grid lines aren't shown unless the block is selected.

@shaunandrews can you post the content you used to get the misaligned content? I wasn't able to reproduce it.

**Comment by jasmussen** [comment]
There was a bit of nuance around _which_ block was selected, to make the gridlines show up. I've fixed it in https://github.com/Automattic/block-experiments/pull/98.
